version: "3"
services:
  backend:
    build: ./backend
    container_name: demo-backend
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: demo-frontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://backend:8080
    depends_on:
      - backend
